// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package bindingValues

import (
	"io"
	"os"
)

// Injectors from wire.go:

func injectFoo() Foo {
	foo := _wireFooValue
	return foo
}

var (
	_wireFooValue = Foo{X: 42}
)

func injectReader() io.Reader {
	reader := _wireFileValue
	return reader
}

var (
	_wireFileValue = os.Stdin
)

// wire.go:

type Foo struct {
	X int
}
