// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package structProviders

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func initializeFooBar() (FooBar, error) {
	foo := ProvideFoo()
	bar := ProvideBar()
	fooBar := FooBar{
		Foo: foo,
		Bar: bar,
	}
	return fooBar, nil
}

// wire.go:

type Foo int

type Bar int

func ProvideFoo() Foo { return Foo(10) }

func ProvideBar() Bar { return Bar(20) }

type FooBar struct {
	Foo Foo
	Bar Bar
}

var Set = wire.NewSet(
	ProvideFoo,
	ProvideBar,
	FooBar{})
